config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :communities
  root to: "public#index"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :account
  validates_presence_of :url, :name, :bio
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :authenticate_account!, except: [ :index, :show ]

  def index
    @communities = Community.all
  end

  def show
  end

  def new
    @community = Community.new
  end

  def create
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/communities/_form.html.erb
<% form_for @community do |form| %>
<div class="form-group">
  <%= label_tag :name %>
  <%= form.text_field :name, class:"form-control" %>
</div>

<% end %>

app/views/communities/index.html.erb
<% if account_signed_in? %>
  <div class="float-right">
    <%= link_to "Create New Community", new_community_path, class: "btn btn-outline-primary" %>
  </div>
<% end %>

<% if @communities.size > 0 %>
  <% @communities.each do |community| %>
    <div class="card">
      <h3><%= link_to community.name %></h3>
      <%= simple_format community.bio %>
    </div>
  <% end %>
<% else %>
<p>No communities to display.</p>
<% end %>

app/views/communities/new.html.erb
<h2>New Community</h2>

<%= render partial: "form" %>

app/views/layouts/_footer.html.erb
footer

app/views/layouts/_header.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 pt-3 pb-3 mb-4 border-bottom">
      <div class="float-right">
        <% if account_signed_in? %>
          <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "btn btn-outline-primary" %>
        <% else %>
          <%= link_to "Log In", new_account_session_path, class: "btn btn-outline-primary" %>
          <%= link_to "Sign Up", new_account_registration_path, class: "btn btn-outline-primary" %>
        <% end %>
      </div>
      <p class="h3">News Pick</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>News Pick</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>
      </div>
    </div>

    <%= render partial: "layouts/footer" %>
  </body>
</html>